### ISSUE TITLE
API url has changed

### ISSUE THREAD

**Issue by shawnbissell** [telephonyresearch/node-opencnam#1]
The v1 url 'https://api.opencnam.com/v1/phone/' 404s and the opencnam returns "Error: No caller ID found." message for all lookups.
I tested the v2 url 'https://api.opencnam.com/v2/phone/' manually and it works as expected.

**Comment by dorfsmay** [comment]
Merged your PR, thanks.

**Comment by tubala** [comment]
Resolved.
