### ISSUE TITLE
Please add support for professional accounts

### ISSUE THREAD

**Issue by shawnbissell** [telephonyresearch/node-opencnam#2]
As i'm sure you are aware Opencnam has a professional account API now which requires an SID and AUTH token in order to make realtime requests. Please consider adding support for this.
https://www.opencnam.com/docs/v2/quickstart

**Comment by mjethani** [comment]
Hi, could you fix the spelling error in the title? Thanks.

**Comment by dorfsmay** [comment]
Feature added in 0.1.3 with PR #4.
